spring.application.name=auth-service

server.port=8087

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8380/realms/agroflowers-realm

keycloak.server-url=http://localhost:8380
keycloak.realm=agroflowers-realm

keycloak.admin-client-id=agroflowers-admin-client
keycloak.admin-client-secret=HUpPYRoQQFk4UVJ1lJWntBZNHWY6XFaY

keycloak.login-client-id=agroflowers-service-client
keycloak.login-client-secret=AQhIbs5ZBW059xYG1czX3QlSlH6XNfxa
