spring.application.name=sales-service

server.port=8086

spring.datasource.url=jdbc:postgresql://localhost:5438/sales_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8380/realms/agroflowers-realm

logistics-service.base-url=http://localhost:8085

resilience4j.circuitbreaker.instances.logisticsService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.logisticsService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.logisticsService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.logisticsService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.logisticsService.waitDurationInOpenState=15s
resilience4j.circuitbreaker.instances.logisticsService.permittedNumberOfCallsInHalfOpenState=3

resilience4j.retry.instances.logisticsService.maxAttempts=3
resilience4j.retry.instances.logisticsService.waitDuration=500ms
resilience4j.retry.instances.logisticsService.retryExceptions=java.io.IOException,org.springframework.web.reactive.function.client.WebClientRequestException

management.endpoints.web.exposure.include=health,circuitbreakers
management.endpoint.health.show-details=always
